### ISSUE TITLE
Compiling as pdf

### ISSUE THREAD

**Issue by roblem** [Hemken/stmd#1]
On Linux and Stata 15, have a working latex distribution (and pandoc) and commands like
```
markstat using test, pdf 
``` 
produce pdf's.

Using `stmd`, I was able to create a word document (although the markstat header syntax wasn't honored) using
```
stmd test.stmd, replace saving(test.docx)
```
but the pdf produced by 
```
stmd test.stmd, replace saving(test.pdf)
```
wasn't able to be opened by any pdf reader I had access to (it didn't have a size of 0, so something was put in it).

**Comment by roblem** [comment]
Upon further inspection, when I try opening the file this error appears:
```
file type plain text document (text/plain) is not supported
```
The `docx` file is of type `text/html`.  Maybe I am mistaken that `stmd` can output Word and pdf files, since no matter the extension it appears that html code is in the file.  But based on [this comment on the stata message board](https://www.statalist.org/forums/forum/general-stata-discussion/general/1483137-stata-markdown-the-stmd-package-from-ssc) it should be possible since pandoc is installed.  Maybe it requires a secondary step in terminal to invoke pandoc on the html output?

**Comment by Hemken** [comment]
Right, stmd is built on top of dyndoc, so in Stata 15 it only creates HTML files.  You should also be able to covert stmd documents to Markdown, and then use Pandoc (there is a separate Stata package for this) to go to PDF, similar to what markstat and rmarkdown do.

With Stata 16 you should be able to produce Word documents directly, although I have not had a chance to test this yet.

**Comment by roblem** [comment]
Thanks. Closing.
